image: docker:latest
services:
  - name: docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - test
  - scan

include:
   - template: SAST.gitlab-ci.yml
   - template: Code-Quality.gitlab-ci.yml
   - template: Security/Dependency-Scanning.gitlab-ci.yml

build:
  image: gradle:jdk11
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

unit-test:
  image: gradle:jdk11
  stage: test
  script: gradle test
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

code_quality:
   stage: scan
   artifacts:
     reports:
       codequality: gl-code-quality-report.json
   after_script:
     - cat gl-code-quality-report.json

eslint-sast:
  stage: scan

nodejs-scan-sast:
  stage: scan

spotbugs-sast:
  stage: scan
  dependencies:
    - build
  script:
    - /analyzer run -compile=false

semgrep-sast:
  rules:
    - when: never

gemnasium-dependency_scanning:
  stage: scan

gemnasium-maven-dependency_scanning:
  stage: scan
  before_script: "chmod +x ./gradlew"

retire-js-dependency_scanning:
  stage: scan
